### ISSUE TITLE
WITH clause not supported

### ISSUE THREAD

**Issue by dongyoungy** [mozafari/verdictdb#120]
SQL WITH clauses that are used to give a sub-query block a name are not supported by VerdictDB.
Trying to parse a query that contains "WITH" clause results with the following error:
```
Exception in thread "main" java.lang.NullPointerException
	at edu.umich.verdict.VerdictMeta.getColumns(VerdictMeta.java:165)
	at edu.umich.verdict.relation.RelationGen$TableSourceExtractor.visitHinted_table_name_item(ExactRelation.java:1010)
	at edu.umich.verdict.relation.RelationGen$TableSourceExtractor.visitHinted_table_name_item(ExactRelation.java:974)
	at edu.umich.verdict.parser.VerdictSQLParser$Hinted_table_name_itemContext.accept(VerdictSQLParser.java:8144)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at edu.umich.verdict.relation.RelationGen$TableSourceExtractor.visitTable_source_item_joined(ExactRelation.java:983)
	at edu.umich.verdict.relation.RelationGen$TableSourceExtractor.visitTable_source_item_joined(ExactRelation.java:974)
	at edu.umich.verdict.parser.VerdictSQLParser$Table_source_item_joinedContext.accept(VerdictSQLParser.java:8072)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at edu.umich.verdict.parser.VerdictSQLBaseVisitor.visitTable_source(VerdictSQLBaseVisitor.java:615)
	at edu.umich.verdict.parser.VerdictSQLParser$Table_sourceContext.accept(VerdictSQLParser.java:8005)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at edu.umich.verdict.relation.RelationGen.visitQuery_specification(ExactRelation.java:735)
	at edu.umich.verdict.relation.RelationGen.visitQuery_specification(ExactRelation.java:552)
	at edu.umich.verdict.parser.VerdictSQLParser$Query_specificationContext.accept(VerdictSQLParser.java:6827)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at edu.umich.verdict.parser.VerdictSQLBaseVisitor.visitQuery_expression(VerdictSQLBaseVisitor.java:510)
	at edu.umich.verdict.parser.VerdictSQLParser$Query_expressionContext.accept(VerdictSQLParser.java:6591)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at edu.umich.verdict.relation.RelationGen.visitSelect_statement(ExactRelation.java:571)
Disconnected from the target VM, address: '127.0.0.1:58854', transport: 'socket'
	at edu.umich.verdict.relation.RelationGen.visitSelect_statement(ExactRelation.java:552)
	at edu.umich.verdict.parser.VerdictSQLParser$Select_statementContext.accept(VerdictSQLParser.java:1914)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at edu.umich.verdict.relation.ExactRelation.from(ExactRelation.java:72)
	at edu.umich.verdict.commercial.designer.VerdictDesigner.readQuery(VerdictDesigner.java:269)
	at edu.umich.verdict.commercial.designer.VerdictDesigner.readQueries(VerdictDesigner.java:65)
	at edu.umich.verdict.commercial.designer.VerdictDesignerMain.main(VerdictDesignerMain.java:68)
ERROR  2018-03-29 19:23:15,259 - edu.umich.verdict.exceptions.VerdictException: org.apache.hive.service.cli.HiveSQLException: Error while compiling statement: FAILED: SemanticException [Error 10001]: Table not found tpcds_bin_partitioned_orc_2.ssales
	at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:256)
	at org.apache.hive.jdbc.Utils.verifySuccessWithInfo(Utils.java:242)
	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:254)
	at edu.umich.verdict.dbms.DbmsJDBC.execute(DbmsJDBC.java:287)
	at edu.umich.verdict.dbms.Dbms.executeJdbcQuery(Dbms.java:145)
	at edu.umich.verdict.dbms.DbmsJDBC.describeTableInResultSet(DbmsJDBC.java:87)
	at edu.umich.verdict.dbms.DbmsJDBC.getColumns(DbmsJDBC.java:128)
	at edu.umich.verdict.VerdictMeta.refreshColumns(VerdictMeta.java:183)
	at edu.umich.verdict.VerdictMeta.getColumns(VerdictMeta.java:163)
	at edu.umich.verdict.relation.RelationGen$TableSourceExtractor.visitHinted_table_name_item(ExactRelation.java:1010)
	at edu.umich.verdict.relation.RelationGen$TableSourceExtractor.visitHinted_table_name_item(ExactRelation.java:974)
	at edu.umich.verdict.parser.VerdictSQLParser$Hinted_table_name_itemContext.accept(VerdictSQLParser.java:8144)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at edu.umich.verdict.relation.RelationGen$TableSourceExtractor.visitTable_source_item_joined(ExactRelation.java:983)
	at edu.umich.verdict.relation.RelationGen$TableSourceExtractor.visitTable_source_item_joined(ExactRelation.java:974)
	at edu.umich.verdict.parser.VerdictSQLParser$Table_source_item_joinedContext.accept(VerdictSQLParser.java:8072)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at edu.umich.verdict.parser.VerdictSQLBaseVisitor.visitTable_source(VerdictSQLBaseVisitor.java:615)
	at edu.umich.verdict.parser.VerdictSQLParser$Table_sourceContext.accept(VerdictSQLParser.java:8005)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at edu.umich.verdict.relation.RelationGen.visitQuery_specification(ExactRelation.java:735)
	at edu.umich.verdict.relation.RelationGen.visitQuery_specification(ExactRelation.java:552)
	at edu.umich.verdict.parser.VerdictSQLParser$Query_specificationContext.accept(VerdictSQLParser.java:6827)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at edu.umich.verdict.parser.VerdictSQLBaseVisitor.visitQuery_expression(VerdictSQLBaseVisitor.java:510)
	at edu.umich.verdict.parser.VerdictSQLParser$Query_expressionContext.accept(VerdictSQLParser.java:6591)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at edu.umich.verdict.relation.RelationGen.visitSelect_statement(ExactRelation.java:571)
	at edu.umich.verdict.relation.RelationGen.visitSelect_statement(ExactRelation.java:552)
	at edu.umich.verdict.parser.VerdictSQLParser$Select_statementContext.accept(VerdictSQLParser.java:1914)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at edu.umich.verdict.relation.ExactRelation.from(ExactRelation.java:72)
	at edu.umich.verdict.commercial.designer.VerdictDesigner.readQuery(VerdictDesigner.java:269)
	at edu.umich.verdict.commercial.designer.VerdictDesigner.readQueries(VerdictDesigner.java:65)
	at edu.umich.verdict.commercial.designer.VerdictDesignerMain.main(VerdictDesignerMain.java:68)
Caused by: org.apache.hive.service.cli.HiveSQLException: Error while compiling statement: FAILED: SemanticException [Error 10001]: Table not found tpcds_bin_partitioned_orc_2.ssales
	at org.apache.hive.service.cli.operation.Operation.toSQLException(Operation.java:388)
	at org.apache.hive.service.cli.operation.SQLOperation.prepare(SQLOperation.java:193)
	at org.apache.hive.service.cli.operation.SQLOperation.runInternal(SQLOperation.java:276)
	at org.apache.hive.service.cli.operation.Operation.run(Operation.java:324)
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementInternal(HiveSessionImpl.java:499)
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementAsync(HiveSessionImpl.java:486)
	at org.apache.hive.service.cli.CLIService.executeStatementAsync(CLIService.java:295)
	at org.apache.hive.service.cli.thrift.ThriftCLIService.ExecuteStatement(ThriftCLIService.java:506)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1437)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1422)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:56)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: org.apache.hadoop.hive.ql.parse.SemanticException:Table not found tpcds_bin_partitioned_orc_2.ssales
	at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.getTable(BaseSemanticAnalyzer.java:1673)
	at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.getTable(BaseSemanticAnalyzer.java:1652)
	at org.apache.hadoop.hive.ql.parse.DDLSemanticAnalyzer.analyzeDescribeTable(DDLSemanticAnalyzer.java:2043)
	at org.apache.hadoop.hive.ql.parse.DDLSemanticAnalyzer.analyzeInternal(DDLSemanticAnalyzer.java:348)
	at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.analyze(BaseSemanticAnalyzer.java:250)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:477)
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1242)
	at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:1229)
	at org.apache.hive.service.cli.operation.SQLOperation.prepare(SQLOperation.java:191)
	... 15 more
```

The query used for the test is following:
```sql
 with ssales as
(select c_last_name
      ,c_first_name
      ,s_store_name
      ,ca_state
      ,s_state
      ,i_color
      ,i_current_price
      ,i_manager_id
      ,i_units
      ,i_size
      ,sum(ss_sales_price) netpaid
from store_sales
    ,store_returns
    ,store
    ,item
    ,customer
    ,customer_address
where ss_ticket_number = sr_ticket_number
  and ss_item_sk = sr_item_sk
  and ss_customer_sk = c_customer_sk
  and ss_item_sk = i_item_sk
  and ss_store_sk = s_store_sk
  and c_birth_country = upper(ca_country)
  and s_zip = ca_zip
and s_market_id=7
group by c_last_name
        ,c_first_name
        ,s_store_name
        ,ca_state
        ,s_state
        ,i_color
        ,i_current_price
        ,i_manager_id
        ,i_units
        ,i_size)
select c_last_name
      ,c_first_name
      ,s_store_name
      ,sum(netpaid) paid
from ssales
where i_color = 'orchid'
group by c_last_name
        ,c_first_name
        ,s_store_name
having sum(netpaid) > (select 0.05*avg(netpaid)
                                 from ssales)
;
```

**Comment by dongyoungy** [comment]
I think I fixed this, but at the same time found a bunch of other problems. I will probably submit a single pull request, containing fixes for all the problems that I have found, including this one.

**Comment by dongyoungy** [comment]
Pull request #125 fixes this issue. I will close this issue once the patch gets merged.
