### ISSUE TITLE
Exceptions on hive

### ISSUE THREAD

**Issue by liming-thu** [mozafari/verdictdb#126]
I'm using the CDH, I created a table of two columns(word, count) in Hive, and ingested about 10 million rows.

I followed the steps in user manual to use the verdict, every step is ok, and I can connected to the Hive successfully([cloudera@quickstart verdict-master]$ ./veeline/bin/veeline -h "hive2://localhost/default;"), and it can correctly process the command: "show tables". However, when I want to create sample of a table, there is an exception:
------------------------------------------------------------------------------------------------------------------------------------------------------------------
verdict:Apache Hive> create sample of wordcount;
INFO   2018-04-06 15:09:57,831 - Create a 1.00% uniform random sample of default.wordcount.
line 1:167 mismatched input 'default' expecting {FORCESEEK, VALUES, ABSOLUTE, APPLY, AUTO, AVG, BASE64, CALLER, CAST, CATCH, CHECKSUM_AGG, COMMITTED, CONCAT, COOKIE, COUNT, COUNT_BIG, DELAY, DELETED, DENSE_RANK, DISABLE, DYNAMIC, ENCRYPTION, FAST, FAST_FORWARD, FIRST, FOLLOWING, FORWARD_ONLY, FULLSCAN, GLOBAL, GO, GROUPING, GROUPING_ID, HASH, INSENSITIVE, INSERTED, ISOLATION, KEEPFIXED, KEYSET, LAST, LEVEL, LOCAL, LOCK_ESCALATION, LOGIN, LOOP, MARK, MAX, MIN, MODIFY, NEXT, NAME, NOCOUNT, NOEXPAND, NORECOMPUTE, NTILE, NUMBER, OFFSET, ONLY, OPTIMISTIC, OPTIMIZE, OUT, OUTPUT, OWNER, PARTITION, PATH, PRECEDING, PRIOR, RANGE, RANK, READONLY, READ_ONLY, RECOMPILE, RELATIVE, REMOTE, REPEATABLE, ROOT, ROW, ROWGUID, ROWS, ROW_NUMBER, SAMPLE, SCHEMABINDING, SCROLL, SCROLL_LOCKS, SELF, SERIALIZABLE, SNAPSHOT, SPATIAL_WINDOW_MAX_CELLS, STATIC, STATS_STREAM, STDEV, STDEVP, SUM, THROW, TIES, TIME, TRY, TYPE, TYPE_WARNING, UNBOUNDED, UNCOMMITTED, UNKNOWN, USING, VAR, VARP, VIEW_METADATA, WORK, XML, XMLNAMESPACES, DOUBLE_QUOTE_ID, BACKTICK_ID, SQUARE_BRACKET_ID, ID, '('}
java.lang.NullPointerException
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitTable_source(Relation.java:644)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitTable_source(Relation.java:292)
        at edu.umich.verdict.VerdictSQLParser$Table_sourceContext.accept(VerdictSQLParser.java:14519)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitQuery_specification(Relation.java:350)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitQuery_specification(Relation.java:292)
        at edu.umich.verdict.VerdictSQLParser$Query_specificationContext.accept(VerdictSQLParser.java:13340)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
        at edu.umich.verdict.VerdictSQLBaseVisitor.visitQuery_expression(VerdictSQLBaseVisitor.java:804)
        at edu.umich.verdict.VerdictSQLParser$Query_expressionContext.accept(VerdictSQLParser.java:13104)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitSelect_statement(Relation.java:325)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitSelect_statement(Relation.java:292)
        at edu.umich.verdict.VerdictSQLParser$Select_statementContext.accept(VerdictSQLParser.java:3721)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitSubquery(Relation.java:442)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitSubquery(Relation.java:292)
        at edu.umich.verdict.VerdictSQLParser$SubqueryContext.accept(VerdictSQLParser.java:11968)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitDerived_table_source_item(Relation.java:690)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitDerived_table_source_item(Relation.java:292)
        at edu.umich.verdict.VerdictSQLParser$Derived_table_source_itemContext.accept(VerdictSQLParser.java:14661)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitTable_source_item_joined(Relation.java:650)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitTable_source_item_joined(Relation.java:292)
        at edu.umich.verdict.VerdictSQLParser$Table_source_item_joinedContext.accept(VerdictSQLParser.java:14586)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitTable_source(Relation.java:644)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitTable_source(Relation.java:292)
        at edu.umich.verdict.VerdictSQLParser$Table_sourceContext.accept(VerdictSQLParser.java:14519)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitQuery_specification(Relation.java:350)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitQuery_specification(Relation.java:292)
        at edu.umich.verdict.VerdictSQLParser$Query_specificationContext.accept(VerdictSQLParser.java:13340)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
        at edu.umich.verdict.VerdictSQLBaseVisitor.visitQuery_expression(VerdictSQLBaseVisitor.java:804)
        at edu.umich.verdict.VerdictSQLParser$Query_expressionContext.accept(VerdictSQLParser.java:13104)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitSelect_statement(Relation.java:325)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitSelect_statement(Relation.java:292)
        at edu.umich.verdict.VerdictSQLParser$Select_statementContext.accept(VerdictSQLParser.java:3721)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitCreate_table_as_select(Relation.java:317)
        at edu.umich.verdict.relation.PrettyPrintVisitor.visitCreate_table_as_select(Relation.java:292)
        at edu.umich.verdict.VerdictSQLParser$Create_table_as_selectContext.accept(VerdictSQLParser.java:5750)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
        at edu.umich.verdict.VerdictSQLBaseVisitor.visitVerdict_statement(VerdictSQLBaseVisitor.java:20)
        at edu.umich.verdict.VerdictSQLParser$Verdict_statementContext.accept(VerdictSQLParser.java:379)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at edu.umich.verdict.relation.Relation.prettyfySql(Relation.java:216)
        at edu.umich.verdict.dbms.Dbms.createUniformRandomSampledTable(Dbms.java:291)
        at edu.umich.verdict.dbms.Dbms.createUniformRandomSampleTableOf(Dbms.java:275)
        at edu.umich.verdict.query.CreateSampleQuery.createUniformRandomSample(CreateSampleQuery.java:119)
        at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:57)
        at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:81)
        at edu.umich.verdict.query.CreateSampleQuery.compute(CreateSampleQuery.java:39)
        at edu.umich.verdict.query.Query.computeResultSet(Query.java:101)
        at edu.umich.verdict.VerdictJDBCContext.execute(VerdictJDBCContext.java:122)
        at edu.umich.verdict.VerdictContext.executeJdbcQuery(VerdictContext.java:119)
        at edu.umich.verdict.jdbc.VerdictStatement.execute(VerdictStatement.java:126)
        at sqlline.Commands.execute(Commands.java:842)
        at sqlline.Commands.sql(Commands.java:752)
        at sqlline.SqlLine.dispatch(SqlLine.java:839)
        at sqlline.SqlLine.begin(SqlLine.java:712)
        at sqlline.SqlLine.start(SqlLine.java:408)
        at sqlline.SqlLine.main(SqlLine.java:300)
------------------------------------------------------------------------------------------------------------------------------------
Do you have any idea where is the problem?

Thank you!

**Comment by pyongjoo** [comment]
@dongyoungy This could happen because "default" is not propertly quoted. I recall this error did not happen when a table is in a non-default schema.

**Comment by dongyoungy** [comment]
@liming-thu I will investigate this issue and let you know once it is fixed.

**Comment by dongyoungy** [comment]
@liming-thu I suspect that you used the old 0.3.0 version instead of the current 0.4.7. 

Could you please get VerdictDB's current master and build it with 'mvn package'? Then, please use './bin/verdict-shell' (instead of veeline, but with same args) to launch the CLI.

**Comment by liming-thu** [comment]
Building successfully, but cannot connected to hive. Here is the output:

[cloudera@quickstart verdictdb-master]$ ./bin/verdict-shell -h "hive2://localhost/default;"
Exception in thread "main" java.lang.ExceptionInInitializerError: SQLLine static class check reports the jline.console.ConsoleReader class was not found. Please ensure JLine is on classpath.
	at sqlline.SqlLine.<clinit>(SqlLine.java:210)

**Comment by dongyoungy** [comment]
@liming-thu Can you try running the following command at the VerdictDB's root directory?
```
jar tvf ./jars/verdict-shell-0.4.7.jar | grep ConsoleReader
```

You should see something like following:
```
[dyoon@MacBook-Pro verdict-public]$ jar tvf ./jars/verdict-shell-0.4.7.jar | grep ConsoleReader
  1197 Mon Jun 26 22:07:34 EDT 2017 jline/console/ConsoleReader$1.class
  1167 Mon Jun 26 22:07:34 EDT 2017 jline/console/ConsoleReader$2.class
  4794 Mon Jun 26 22:07:34 EDT 2017 jline/console/ConsoleReader$3.class
  1330 Mon Jun 26 22:07:34 EDT 2017 jline/console/ConsoleReader$State.class
 55989 Mon Jun 26 22:07:34 EDT 2017 jline/console/ConsoleReader.class
  1439 Mon Jun 26 22:07:34 EDT 2017 jline/console/internal/ConsoleReaderInputStream$ConsoleEnumeration.class
  1169 Mon Jun 26 22:07:34 EDT 2017 jline/console/internal/ConsoleReaderInputStream$ConsoleLineInputStream.class
  1207 Mon Jun 26 22:07:34 EDT 2017 jline/console/internal/ConsoleReaderInputStream.class
```

**Comment by liming-thu** [comment]
Yes, exactly:

[cloudera@quickstart verdictdb-master]$ jar tvf ./jars/verdict-shell-0.4.7.jar | grep ConsoleReader
  1197 Mon Jun 26 22:07:34 PDT 2017 jline/console/ConsoleReader$1.class
  1167 Mon Jun 26 22:07:34 PDT 2017 jline/console/ConsoleReader$2.class
  4794 Mon Jun 26 22:07:34 PDT 2017 jline/console/ConsoleReader$3.class
  1330 Mon Jun 26 22:07:34 PDT 2017 jline/console/ConsoleReader$State.class
 55989 Mon Jun 26 22:07:34 PDT 2017 jline/console/ConsoleReader.class
  1439 Mon Jun 26 22:07:34 PDT 2017 jline/console/internal/ConsoleReaderInputStream$ConsoleEnumeration.class
  1169 Mon Jun 26 22:07:34 PDT 2017 jline/console/internal/ConsoleReaderInputStream$ConsoleLineInputStream.class
  1207 Mon Jun 26 22:07:34 PDT 2017 jline/console/internal/ConsoleReaderInputStream.class

**Comment by dongyoungy** [comment]
@liming-thu Hmmm, that's weird. The error you are getting is basically complaining that it cannot find the ConsoleReader class in the classpath, but the jar file contains it so it should be able to find..

Could you try the following instead?
```
java -cp "./jars/*" sqlline.SqlLine
```

**Comment by liming-thu** [comment]
There's sth wrong:

[cloudera@quickstart verdictdb-master]$ java -cp "./jars/*" sqlline.SqlLine
Exception in thread "main" java.lang.ExceptionInInitializerError: SQLLine static class check reports the jline.console.ConsoleReader class was not found. Please ensure JLine is on classpath.
	at sqlline.SqlLine.<clinit>(SqlLine.java:210)

**Comment by dongyoungy** [comment]
The previous command launches the CLI successfully for me. I can launch the CLI and get the usage message with either of the following commands as well:
```
java -cp "./jars/verdict-shell-0.4.7.jar" sqlline.SqlLine
java -jar "./jars/verdict-shell-0.4.7.jar" sqlline.SqlLine
```

May I ask what your current Java version is?

**Comment by liming-thu** [comment]
[cloudera@quickstart verdictdb-master]$ java -version
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

**Comment by liming-thu** [comment]
The commands:
java -cp "./jars/verdict-shell-0.4.7.jar" sqlline.SqlLine
java -jar "./jars/verdict-shell-0.4.7.jar" sqlline.SqlLine
also can launch the CLI in my machine, but cannot connect to the hive:
java -jar "./jars/verdict-shell-0.4.7.jar" sqlline.SqlLine -h "hive2://localhost/default;"
edu.umich.verdict.jdbc.Driver
Unknown command: properties sqlline.SqlLine

    __     __           _ _      _
    \ \   / /__ _ __ __| (_) ___| |_
     \ \ / / _ \ '__/ _` | |/ __| __|
      \ V /  __/ | | (_| | | (__| |_ 
       \_/ \___|_|  \__,_|_|\___|\__|     version 0.4.7

Notes:
1. Entering "!quit" terminates this interactive shell.
2. All other queries (except for !quit) must terminate with a semicolon (;).
3. You can change Verdict's log level to DEBUG by entering:
   > set loglevel=debug;
   Please turn this debug option on for reporting issues to the developers. The other possible log levels
   are "info", "warn", and "error".
4. By default, all queries issued in verdict-shell are processed by Verdict. However, if you want to disable this
   behavior, enter:
   > set bypass=true;
   Then, Verdict passes all queries directly to your database without Verdict's query rewriting. You can
   re-enable Verdict's rewriting by entering:
   > set bypass=false;
5. Basic commands include:
   > show databases;
   > show tables [in schema];
   > use schema;
   > describe [schema.]table;
   > create uniform sample of [schema.]table;        (may take a while)
   > select count(*) from [schema.]table;
 
For more information, please visit http://verdictdb.org

verdict:no-db> show tables;
No current connection

**Comment by dongyoungy** [comment]
@liming-thu 
1. please 'git pull' and rebuild with 'mvn package'
2. check directory jars and make sure that you have three files like following:
```
[dyoon@MacBook-Pro verdict-public]$ ls -l jars
total 236672
-rw-r--r--  1 dyoon  staff  59923256 Apr  7 02:25 verdict-jdbc-0.4.7.jar
-rw-r--r--  1 dyoon  staff    394392 Apr  7 02:25 verdict-shell-0.4.7.jar
-rw-r--r--  1 dyoon  staff  59150751 Apr  7 02:25 verdict-spark-lib-0.4.7.jar
```
3. launch CLI with ./bin/verdict-shell. e.g.,
```
$ ./bin/verdict-shell -h "hive2://localhost:10000/default"
```

If the above steps still do not work, I would like to have a look at the log from 'mvn package' and also it would be good to know the version of Hive that you are using currently. Thanks.

**Comment by liming-thu** [comment]
[errmsg.txt](https://github.com/mozafari/verdictdb/files/1886794/errmsg.txt)
[mvn_build_log.txt](https://github.com/mozafari/verdictdb/files/1886795/mvn_build_log.txt)
The hive version:
Subversion file:///data/jenkins/workspace/generic-package-rhel64-6-0/topdir/BUILD/hive-1.1.0-cdh5.13.0 -r Unknown
Compiled by jenkins on Wed Oct 4 11:06:55 PDT 2017
From source with checksum 4c9678e964cc1d15a0190a0a1867a837

BTW, I changed my database name and connected to the database and created samples using the verdict 0.3.
Thank you!

**Comment by dongyoungy** [comment]
@liming-thu 
It looks like the problem is that your Hive version (1.1.0) is older than hive-jdbc client used by the current version of VerdictDB (i.e., 1.2.1). If you want to use the current version of VerdictDB (which I recommend), what you can do is the following:

1. open pom.xml
2. find the <hive-jdbc.version> tag under <properties>:
```xml
        <hive-jdbc.version>1.2.1</hive-jdbc.version>
```
3. change the version to the Hive version that you are using (in your case 1.1.0)
4. recompile VerdictDB with 'mvn package'

Please let us know if you have any other questions.

**Comment by liming-thu** [comment]
Great！Problem solved perfectly, thank you very much! @dongyoungy @pyongjoo

**Comment by barzan** [comment]
@dongyoungy @pyongjoo can you please include a check in VerdictDB's code or its installer so whenever the drivers or other dependencies do not meet the version requirements it outputs a self-explanatory error so users won't have to guess what's wrong?

Thanks

**Comment by dongyoungy** [comment]
#128 added an error message that notifies users to check the server URL or client's JDBC version when unable to connect to the database.
