### ISSUE TITLE
Out of memory error while running tpc-h query 9

### ISSUE THREAD

**Issue by pyongjoo** [mozafari/verdictdb#158]
Hello community organizers,

We are currenting test VerdictDB with tpc-h query but we get an OOM error. Hope you could help check the issue. 

We create sample table with default setting, thus there is a sample table for each table columns. Then we test with tpc-h query 9(query is attached at the end of email) but an error is raised: 
    java.lang.OutOfMemoryError: GC overhead limit exceeded
         at java.util.Arrays.copyOf(Arrays.java:3181)
         at java.util.ArrayList.toArray(ArrayList.java:380)
         at java.util.ArrayList.<init>(ArrayList.java:178)
         at edu.umich.verdict.relation.SampleGroup.duplicate(SampleGroup.java:118)
         at edu.umich.verdict.relation.SamplePlan.duplicate(SamplePlan.java:55)
         at edu.umich.verdict.relation.SamplePlan.createByMerge(SamplePlan.java:119)
         at edu.umich.verdict.relation.SamplePlans.consolidateNewExpr(SamplePlans.java:64)
         at edu.umich.verdict.relation.ExactRelation.consolidate(ExactRelation.java:421)

In ExactRelation.consolidate method, I find that the size of sample group for each candidates list is 6095. And then in SamplePlans.consolidateNewExpr method, there is a nested loop with size of 6095 * 6095. Error would be raised during plan merge in the nested loop. 
And it seems that the method nBestSamples of relation does not produce a result set of size n. 

Could you help check the issue?

Thank you& Best regards,
Haohua Li

tpc-h query 9: 
select
    nation,
    o_year,
    sum(amount) as sum_profit
from
    (
        select
            n_name as nation,
            substr(o_orderdate,1,4) as o_year,
            l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount
        from
            tpch_supplier s
            join tpch_lineitem l on s.s_suppkey = l.l_suppkey
            join tpch_partsupp ps on ps.ps_suppkey = l.l_suppkey and ps.ps_partkey = l.l_partkey
            join tpch_part p on p.p_partkey = l.l_partkey
            join tpch_orders o on o.o_orderkey = l.l_orderkey
            join tpch_nation n on s.s_nationkey = n.n_nationkey

        where
        p_name like '%green%'
    ) profit
group by
    nation,
    o_year
order by
    nation,
    o_year desc
limit 999999;

**Comment by pyongjoo** [comment]
This error must not exist anymore since we updated our core logic.
