### ISSUE TITLE
Failed but results were good actually

### ISSUE THREAD

**Issue by pyongjoo** [mozafari/verdictdb#181]
Interestingly, the outputs seem to be identical (i.e., 1:1), but JUnit says they are different. The only difference is that the getObject() method is called one more time after printing out those values.

```
bitvarycol >> 1 : 1
int8col >> 1 : 1
boolcol >> true : true
charactercol >> 1234 : 1234
charactervcol >> 1234 : 1234
intcol >> 1 : 1
int4col >> 1 : 1
doublepcol >> 1.0 : 1.0
decimalcol >> 1.00 : 1.00
float4col >> 1.0 : 1.0
int2col >> 1 : 1
serial2col >> 1 : 1
serial4col >> 1 : 1
timetzcol >> 00:00:01 : 00:00:01
timestamptzcol >> 2018-12-31 00:00:01.0 : 2018-12-31 00:00:01.0
serial8col >> 1 : 1
bigintcol >> null : null
bigserialcol >> 1 : 1
bitcol >> null : null
varbitcol >> null : null
booleancol >> null : null
boxcol >> null : null
byteacol >> null : null
charcol >> null : null
varcharcol >> null : null
cidrcol >> null : null
circlecol >> null : null
datecol >> null : null
float8col >> null : null
inetcol >> null : null
integercol >> null : null
jsoncol >> null : null
linecol >> null : null
lsegcol >> null : null
macaddrcol >> null : null
macaddr8col >> null : null
moneycol >> null : null
numericcol >> null : null
pathcol >> null : null
pointcol >> null : null
polygoncol >> null : null
realcol >> null : null
smallintcol >> null : null
smallserialcol >> 1 : 1
serialcol >> 1 : 1
textcol >> null : null
timecol >> null : null
timestampcol >> null : null
uuidcol >> null : null
xmlcol >> null : null
bitvarycol >> null : null
int8col >> null : null
boolcol >> null : null
charactercol >> null : null
charactervcol >> null : null
intcol >> null : null
int4col >> null : null
doublepcol >> null : null
decimalcol >> null : null
float4col >> null : null
int2col >> null : null
serial2col >> 1 : 1
serial4col >> 1 : 1
timetzcol >> null : null
timestamptzcol >> null : null
serial8col >> 1 : 1
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.975 sec <<< FAILURE! - in org.verdictdb.jdbc41.JdbcQueryDataTypeForAllDatabasesTest
testDataType[redshift](org.verdictdb.jdbc41.JdbcQueryDataTypeForAllDatabasesTest)  Time elapsed: 0.837 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.verdictdb.jdbc41.JdbcQueryDataTypeForAllDatabasesTest.testDataType(JdbcQueryDataTypeForAllDatabasesTest.java:260)
```

**Comment by pyongjoo** [comment]
It looks like this error was due to the random ordering of Redshift rows.

**Comment by pyongjoo** [comment]
This error was fixed by https://github.com/mozafari/verdictdb/pull/183
