### ISSUE TITLE
create scramble does not create the schema automatically

### ISSUE THREAD

**Issue by pyongjoo** [mozafari/verdictdb#219]
I was testing something else with Redshift. An error was thrown saying that the schema does not exist. We can issue "create schema if not exist" in the scrambling coordinator.

The following is the log:
```
Caused by: org.verdictdb.exception.VerdictDBDbmsException: Issued the following query: create table "tpch10g_vldb19"."lineitem_uniform_scramble" COMPOUND SORTKEY ("verdictdbblock") as select t."l_orderkey", t."l_partkey", (cut) as t
[Amazon](500310) Invalid operation: schema "tpch10g_vldb19" does not exist;
	at org.verdictdb.connection.JdbcConnection.executeSingle(JdbcConnection.java:229)
	at org.verdictdb.connection.JdbcConnection.execute(JdbcConnection.java:135)
	at org.verdictdb.connection.ConcurrentJdbcConnection.execute(ConcurrentJdbcConnection.java:128)
	at org.verdictdb.connection.CachedDbmsConnection.execute(CachedDbmsConnection.java:45)
	at org.verdictdb.core.execplan.ExecutableNodeRunner.execute(ExecutableNodeRunner.java:221)
	at org.verdictdb.core.execplan.ExecutableNodeRunner.executeAndBroadcast(ExecutableNodeRunner.java:204)
	at org.verdictdb.core.execplan.ExecutableNodeRunner.run(ExecutableNodeRunner.java:146)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dongyoungy** [comment]
This has been fixed in #223
