### ISSUE TITLE
NullPointerException when VerdictStatement::executeQuery is used for queries that yield no results (e.g., DDL - CREATE TABLE..)

### ISSUE THREAD

**Issue by dongyoungy** [mozafari/verdictdb#263]
When VerdictStatement's executeQuery() method is used for say DDL commands like CREATE TABLE, which returns no resultset, it will cause NullPointerException like the following:

```java
java.lang.NullPointerException
	at org.verdictdb.jdbc41.VerdictResultSet.<init>(VerdictResultSet.java:58)
	at org.verdictdb.jdbc41.VerdictStatement.executeQuery(VerdictStatement.java:60)
	at org.verdictdb.core.scramblingquerying.RedshiftUniformScramblingQueryTest.setupRedshift(RedshiftUniformScramblingQueryTest.java:110)
	at org.verdictdb.core.scramblingquerying.RedshiftUniformScramblingQueryTest.setupDatabases(RedshiftUniformScramblingQueryTest.java:79)
```

We need to handle this case properly.

@pyongjoo This case does not seem to be specific to Presto. As you can see, I replicated this error with RedShift, simply changing execute() to executeQuery() for "CREATE SCRAMBLE TABLE" in one of our test cases.

**Comment by pyongjoo** [comment]
I see. Is this something that can be prevented by rejecting DDL statements passed to executeQuery()? If so, can you add a logic for it?
