### ISSUE TITLE
FYI, QueryResultAccuracyEstimationFromDifference caused the following IndexOutOfBoundsException before the temporary fix:

### ISSUE THREAD

**Issue by pyongjoo** [mozafari/verdictdb#294]
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.verdictdb.coordinator.QueryResultAccuracyEstimatorFromDifference.checkConverge(QueryResultAccuracyEstimatorFromDifference.java:64)
	at org.verdictdb.coordinator.QueryResultAccuracyEstimatorFromDifference.isLastResultAccurate(QueryResultAccuracyEstimatorFromDifference.java:45)
	at org.verdictdb.coordinator.ExecutionContext.sql(ExecutionContext.java:152)
	at org.verdictdb.coordinator.ExecutionContext.sql(ExecutionContext.java:123)
	at org.verdictdb.jdbc41.VerdictStatement.executeQuery(VerdictStatement.java:135)
	at org.verdictdb.jdbc41.PrestoSpatialQueryTest.runSimpleSelectSTContainsTest(PrestoSpatialQueryTest.java:171)
```

_Originally posted by @dongyoungy in https://github.com/mozafari/verdictdb/pull/293#issuecomment-437200212_

**Comment by pyongjoo** [comment]
@Beastjoe Can you take a look at this issue?
