### ISSUE TITLE
Supporting "show tables in schema" query

### ISSUE THREAD

**Issue by pyongjoo** [mozafari/verdictdb#296]
When I tried the query, I received the following error. I think we need two things:
1. Throw an error that makes sense (saying "VerdictDB does not support the query") if the query does not belong to the queries we support.
2. Actually support the query.

```
>>> result = verdict_conn.sql('show tables in default')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/pyverdict/verdictcontext.py", line 32, in sql
    return verdictresult.SingleResultSet(java_resultset, self)
  File "/anaconda3/lib/python3.6/site-packages/pyverdict/verdictresult.py", line 27, in __init__
    (heading, column_inttypes, column_types, rows) = self._read_all(resultset)
  File "/anaconda3/lib/python3.6/site-packages/pyverdict/verdictresult.py", line 173, in _read_all
    column_count = resultset.getColumnCount()
  File "/anaconda3/lib/python3.6/site-packages/py4j-0.10.7-py3.6.egg/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/anaconda3/lib/python3.6/site-packages/py4j-0.10.7-py3.6.egg/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o2.getColumnCount.
: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.verdictdb.coordinator.VerdictSingleResultFromListData.getColumnCount(VerdictSingleResultFromListData.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dongyoungy** [comment]
The query is already supported. The problem here is with VerdictSingleResultFromListData not handling 'empty set' result correctly. I created PR #300 for the fix.
