### ISSUE TITLE
TPCH queries

### ISSUE THREAD

**Issue by solangepaz** [mozafari/verdictdb#304]
Hi,
How can I apply verdict-tutorial to tpch queries? Is an example possible? Because what is there is very simple and only uses a table.
I want to for example use Q16, but I'm having errors because of Java.
```
Exception in thread "main" java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2519)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at VerdictTutorialMain.runQuery(VerdictTutorialMain.java:96)
        at VerdictTutorialMain.main(VerdictTutorialMain.java:73)
```

**Comment by pyongjoo** [comment]
Our test cases already include most TPC-H queries, so it should work. In your case, it simply seems to be String.format() error, which is nothing to do with VerdictDB itself. If you copy and paste the whole line, I can take a look.
