### ISSUE TITLE
Occasional scaling error

### ISSUE THREAD

**Issue by pyongjoo** [mozafari/verdictdb#316]
Often the scaled answers are not identical to the expected answers.

An example is: https://circleci.com/gh/mozafari/verdictdb/3092

**Comment by pyongjoo** [comment]
@Beastjoe I think this is something to do with inMemoryAggregate, but haven't found its cause. If you have any suggestions, let me know.

**Comment by Beastjoe** [comment]
I have encountered this problem before, like https://circleci.com/gh/mozafari/verdictdb/2226. 
It seems the redshift tests are more likely to go wrong.

**Comment by dongyoungy** [comment]
FYI, here are the ones that I have encountered:

```
queryCountDistinct3Test - org.verdictdb.coordinator.PrestoTpchSelectQueryCoordinatorTest
java.lang.AssertionError: expected:<2606> but was:<2868>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.verdictdb.coordinator.PrestoTpchSelectQueryCoordinatorTest.queryCountDistinct3Test(PrestoTpchSelectQueryCoordinatorTest.java:194)
```

```
query17Test - org.verdictdb.coordinator.PostgreSqlTpchSelectQueryCoordinatorTest
java.lang.AssertionError: expected:<5371277.948571429> but was:<6409089.335714285>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at org.verdictdb.coordinator.PostgreSqlTpchSelectQueryCoordinatorTest.query17Test(PostgreSqlTpchSelectQueryCoordinatorTest.java:403)
```

**Comment by pyongjoo** [comment]
A fix has been posted (hopefully): https://github.com/mozafari/verdictdb/pull/317
