### ISSUE TITLE
NullPointerException on simple count query..

### ISSUE THREAD

**Issue by commercial-hippie** [mozafari/verdictdb#321]
Hi!

When I run the following query verdict throws a nullpointer..

```
SELECT count(*) AS "count" FROM poi_table_orc WHERE day >= 16 AND day <= 30 AND place_type = 'golf_course'
```
If I remove the `place_type = 'golf_course'` part of the query then it runs correctly.  I'll test the query tomorrow on the instance that we created for you to run tests on and add more information here. 

```
Error running instance method java.lang.NullPointerException
	at org.verdictdb.coordinator.QueryResultAccuracyEstimatorFromDifference.checkConverge(QueryResultAccuracyEstimatorFromDifference.java:194)
	at org.verdictdb.coordinator.QueryResultAccuracyEstimatorFromDifference.isLastResultAccurate(QueryResultAccuracyEstimatorFromDifference.java:119)
	at org.verdictdb.coordinator.ExecutionContext.sqlSelectQuery(ExecutionContext.java:249)
	at org.verdictdb.coordinator.ExecutionContext.sql(ExecutionContext.java:160)
	at org.verdictdb.jdbc41.VerdictStatement.execute(VerdictStatement.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

Thanks!

**Comment by pyongjoo** [comment]
We have encountered a similar error in our internal tests, but the fix has not been pushed.

@Beastjoe Can you share the current status on this issue?

**Comment by Beastjoe** [comment]
Sorry for the delay. I will fix this tonight.

**Comment by pyongjoo** [comment]
The related fix has been merged to master: https://github.com/mozafari/verdictdb/pull/322

**Comment by commercial-hippie** [comment]
Thank you :+1: :smile:

**Comment by pyongjoo** [comment]
@commercial-hippie Note that if the filtering predicates do not output any rows, VerdictDB will simply process the entire scramble to produce an accurate answer (in terms of relative errors).  However, your business logic might not want this. That is, you may want the execution to finish early if the absolute difference is expected to be small. In this case, please contact me to discuss how to better suit your case.
