### ISSUE TITLE
ERROR: relation "pg_partitioned_table" does not exist

### ISSUE THREAD

**Issue by solangepaz** [mozafari/verdictdb#382]
Hello,
I'm using VerdictDB with PostgreSQL, but I'm getting this error. What could be at its source?

```
Creating a scrambled table for customer...
21:56:55.289 [com.speedment.example.App.main()] INFO  o.v.c.ScramblingCoordinator - Starts to create a new UNIFORM scramble tpch.customer_scramble from tpch.customer
21:56:55.290 [com.speedment.example.App.main()] INFO  o.v.c.ScramblingCoordinator - Method: UNIFORM
21:56:55.292 [com.speedment.example.App.main()] INFO  o.v.c.ScramblingCoordinator - Relative size: 1.000000 (or equivalently, 100.0000 %)
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.verdictdb.core.execplan.ExecutableNodeRunner.execute(ExecutableNodeRunner.java:464)
        at org.verdictdb.core.execplan.ExecutableNodeRunner.executeAndBroadcast(ExecutableNodeRunner.java:409)
        at org.verdictdb.core.execplan.ExecutableNodeRunner.run(ExecutableNodeRunner.java:277)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.verdictdb.exception.VerdictDBDbmsException: Issued the following query: select partattrs from pg_partitioned_table join pg_class on pg_class.relname='customer' and pg_class.oid = pg_partitioned_table.partrelid join information_schema.tables on table_schema='tpch' and table_name = 'customer'
ERROR: relation "pg_partitioned_table" does not exist
  Position: 23
        at org.verdictdb.connection.JdbcConnection.executeSingle(JdbcConnection.java:222)
        at org.verdictdb.connection.JdbcConnection.execute(JdbcConnection.java:182)
        at org.verdictdb.connection.JdbcConnection.executeQuery(JdbcConnection.java:228)
        at org.verdictdb.connection.JdbcConnection.getPartitionColumns(JdbcConnection.java:348)
        at org.verdictdb.connection.ConcurrentJdbcConnection.getPartitionColumns(ConcurrentJdbcConnection.java:121)
        at org.verdictdb.connection.CachedDbmsConnection.getPartitionColumns(CachedDbmsConnection.java:163)
        ... 8 more
org.verdictdb.exception.VerdictDBValueException
        at org.verdictdb.core.execplan.ExecutableNodeRunner.execute(ExecutableNodeRunner.java:472)
        at org.verdictdb.core.execplan.ExecutableNodeRunner.executeAndBroadcast(ExecutableNodeRunner.java:409)
        at org.verdictdb.core.execplan.ExecutableNodeRunner.run(ExecutableNodeRunner.java:277)
        at java.lang.Thread.run(Thread.java:748)
[WARNING]
java.lang.RuntimeException: org.verdictdb.exception.VerdictDBValueException
        at org.verdictdb.core.resulthandler.ExecutionTokenReader.takeOne(ExecutionTokenReader.java:53)
        at org.verdictdb.core.resulthandler.ExecutionTokenReader.next(ExecutionTokenReader.java:83)
        at org.verdictdb.core.execplan.ExecutablePlanRunner.runTillEnd(ExecutablePlanRunner.java:61)
        at org.verdictdb.coordinator.ScramblingCoordinator.scramble(ScramblingCoordinator.java:310)
        at org.verdictdb.coordinator.ScramblingCoordinator.scramble(ScramblingCoordinator.java:193)
        at org.verdictdb.coordinator.ExecutionContext.sql(ExecutionContext.java:182)
        at org.verdictdb.jdbc41.VerdictStatement.execute(VerdictStatement.java:109)
        at com.speedment.example.App.createScrambleTable(App.java:61)
        at com.speedment.example.App.main(App.java:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.verdictdb.exception.VerdictDBValueException
        at org.verdictdb.core.execplan.ExecutableNodeRunner.execute(ExecutableNodeRunner.java:472)
        at org.verdictdb.core.execplan.ExecutableNodeRunner.executeAndBroadcast(ExecutableNodeRunner.java:409)
        at org.verdictdb.core.execplan.ExecutableNodeRunner.run(ExecutableNodeRunner.java:277)
        ... 1 more

```

**Comment by solangepaz** [comment]
It is an error in the PostgreSQL version. In version 10 the error disappears.
