### ISSUE TITLE
ERROR: relation "placeholderSchema_3_0.placeholderTable_3_0" does not exist

### ISSUE THREAD

**Issue by solangepaz** [mozafari/verdictdb#384]
When I try to run this query with verdictdb in java through a postgresql database:
```
select
	s_name,
	s_address, sum(s_suppkey*s_nationkey)
from
	supplier,
	nation
where
	s_suppkey in (
		select
			ps_suppkey
		from
			partsupp
		where
			ps_partkey in (
				select
					p_partkey
				from
					part
				where
					p_name like 'forest%'
			)
	)
	and s_nationkey = n_nationkey
	and n_name = 'CANADA'
	group by s_name, s_address
	
```
I have this error:
`org.verdictdb.exception.VerdictDBDbmsException: Issued the following query: select vt1."s_name" as "s_name", vt1."s_address" as "s_address", sum(vt1."s_suppkey" * vt1."s_nationkey") as "agg0", vt1."s_name" as "verdictdb_group_by0", vt1."s_address" as "verdictdb_group_by1", vt1."verdictdbtier" as "verdictdb_tier_alias_518478_0", vt2."verdictdbtier" as "verdictdb_tier_alias_518478_1" from "tpch1g"."supplier_scramble" as vt1, "tpch1g"."nation_scramble" as vt2 where ((((vt1."s_suppkey" in (select vt3."ps_suppkey" as "ps_suppkey" from "tpch1g"."partsupp" as vt3 where vt3."ps_partkey" in (select verdictdb_alias_518478_4."p_partkey" as "p_partkey" from "placeholderSchema_3_0"."placeholderTable_3_0" as verdictdb_alias_518478_4))) and (vt1."s_nationkey" = vt2."n_nationkey")) and (vt2."n_name" = 'CANADA')) and (vt1."verdictdbblock" = 0)) and (vt2."verdictdbblock" = 0) group by vt1."s_name", vt1."s_address", vt1."verdictdbtier", vt2."verdictdbtier"
ERROR: relation "placeholderSchema_3_0.placeholderTable_3_0" does not exist
  Position: 579
        at org.verdictdb.connection.JdbcConnection.executeSingle(JdbcConnection.java:222)
        at org.verdictdb.connection.JdbcConnection.execute(JdbcConnection.java:182)
        at org.verdictdb.connection.ConcurrentJdbcConnection.execute(ConcurrentJdbcConnection.java:143)
        at org.verdictdb.connection.CachedDbmsConnection.execute(CachedDbmsConnection.java:49)
        at org.verdictdb.core.execplan.ExecutableNodeRunner.execute(ExecutableNodeRunner.java:435)
        at org.verdictdb.core.execplan.ExecutableNodeRunner.executeAndBroadcast(ExecutableNodeRunner.java:409)
        at org.verdictdb.core.execplan.ExecutableNodeRunner.run(ExecutableNodeRunner.java:277)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by pyongjoo** [comment]
Thanks for the report.

VerdictDB should not have approximated this query in the first place...
